/// Flutter icons SIGicons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SIGicons
///      fonts:
///       - asset: fonts/SIGicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SIGicons {
  SIGicons._();

  static const _kFontFam = 'SIGicons';
  static const String? _kFontPkg = null;

  static const IconData editfilled_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editoutlined_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationfilled_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationoutlined_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addcheck_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addfilled_icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowleft_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bordercoloroutlined_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatbubble_icon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkcircle_icon = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doublearrowup_icon = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addboxoutlined_icon = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bordercolorfilled_icon = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_icon = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowright_icon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps_icon = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData night_icon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData day_icon = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_icon = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selectprd_icon = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData double_arrow_left = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sig_logo = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsoutlined_icon = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settingsfilled_icon = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
